### PR TITLE
Move CI from Travis to Github Actions

### LINKED ISSUE #266: Fix CI
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

_Originally posted by @CnlPepper in https://github.com/cherab/core/issues/262#issuecomment-778169307_

Putting this in a new issue so it doesn't get lost in #262

### LINKED ISSUE #280: Incorrect raysect version in setup.py
Development branch now requires raysect==0.7.1 (blend functions have moved), but setup.py still has raysect==0.7 (which pulls in 0.7.0).

This also means installation using pyproject.toml is broken, as pip then pulls in raysect==0.7.0 to build, and 0.7.1 isn't available on PyPI. That can be worked around by passing the --no-use-pep517 flag to `pip install` for now.

### PR DESCRIPTION
**Pull request by StanczakDominik**
Closes #266. Also closes #280 while I'm at it.

https://github.com/StanczakDominik/core/runs/2486406106?check_suite_focus=true shows how it'd look like. I *think* I set up everything correctly, I'm still waiting on the CI results (raysect's a hefty dependency! 😄) though.

PR builds won't trigger until this is merged into dev. I also expect 5fd23ab will need to be cherry-picked into master for tests to run there as well.

I would also suggest enabling tests for python versions up to 3.9. I wanted the PR to be a more literal Travis -> GH Actions translation, though.

### CODE REVIEW

**Comment by StanczakDominik** [comment]
https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions shows that Github actions is limited to 2000 free CI minutes a month (by default, it just stops running afterwards). Given that raysect takes about 15min to compile on a from-github install, with 6 entries in the testing array, I suspect you're going to burn through that limit pretty quickly. *(not to mention the environmental impact!)*

AFAIK with Cython, you can create pre-compiled builds that you can upload to PyPI, am I right? Because if so, an alternative would be to pin cherab-dev to a raysect release, then have a single job in the matrix testing with the github version. If the minutes limit is then still an issue, you could have a label or comment manually trigger that particular CI build. Or you could limit github-based raysect builds to periodic builds on the dev branch itself.

Also, I messed the config up by mistake - https://github.com/StanczakDominik/core/actions/runs/804309594 this run should actually test things :)

**Comment by jacklovell** [comment]
Thanks for this @StanczakDominik! Yes, we've previously struggled with the issue of long Raysect build times using up free minutes: ReadtheDocs has a similar limitation. We actually moved away from pinning development to a released version of Raysect, because Cherab development often depends on features in Raysect development.

I'm assigning @CnlPepper and @mattngc to this, as they have ownership of the repository and are best placed to decide on our CI approach.

**Comment by StanczakDominik** [comment]
That's fair, of course :)

> We actually moved away from pinning development to a released version of Raysect, because Cherab development often depends on features in Raysect development.

Yeah, I can that! Perhaps one could, however, sidestep this issue with something like `raysect-nightly` on PyPI that works like https://pypi.org/project/tf-nightly/#history, auto-builds and auto-releases (and yeah, I'm volunteering to implement that 😉 haven't quite done that with Cython, but I'd be curious to try) from every commit to the `raysect/development` branch, and then depend on raysect-nightly in CI tests on the development branch here. That way, you compile raysect once per every commit on raysect/dev and only compile cherab in CI here.

**Comment by jacklovell** [comment]
@CnlPepper could you take a look at this please? I believe only you and @mattngc can make changes to the CI configuration for the Cherab repos.

**Comment by CnlPepper** [comment]
> @CnlPepper could you take a look at this please? I believe only you and @mattngc can make changes to the CI configuration for the Cherab repos.

Hi Jack, we've decided to give you co-owner access to the cherab organisation. You should then be able to set relevant permissions as required. We are simply unable to provide the level of support you would like at present due to company commitments. I'll still be free to have a look over any code/changes but we should no longer be holding up improvements to the CI etc...

**Comment by CnlPepper** [comment]
@mattngc and I are willing to pay for the CI for raysect and cherab as a company sponsorship, so (within sensible limits) feel free to setup what you want and we'll see what the cost will come to.

**Comment by jacklovell** [comment]
@StanczakDominik apologies for the delay in this. Could you please merge the latest development branch of Cherab and run the CI again to check? 

Overall this looks pretty good to me, though I would like to test on more recent Python versions (3.8 and 3.9) and Numpy versions (1.21 should be added as latest stable). 

I take your point about the time spent building raysect every time being a huge sink of CPU seconds, and I like the idea of having a development/nightly wheel. That discussion should go over on the raysect repository though. As an interim solution could we at least build raysect once for each Python version, and re-use the wheel for each entry in the numpy matrix?

I would also like to build the documentation in the CI. There is a `./dev/build_docs.sh` script which should be run after `./dev/build.sh`, and that puts its output in `./docs/build/html`. That process is much faster than the build or the tests, and only needs to be done for one of the Python/Numpy combinations.

**Comment by StanczakDominik** [comment]
No worries! I am actually on vacation now, though, so I'll get back to this in a week from so :)

**Comment by jacklovell** [comment]
I'm merging this into a test branch so we can ensure there are no surprises when the CI runs. Assuming all is well I'll then merge it into the development branch. Thanks again @StanczakDominik for helping us with this.

**Review by jacklovell — APPROVED** [review]

**Pull request merged**
