### PR TITLE
Add cylindrical and periodic mappers

### PR DESCRIPTION
**Pull request by vsnever**
This solves #387 by extending the collection of Cherab mappers with `PeriodicMapper#D`, `VectorPeriodicMapper#D`, `CylindricalMapper` and `VectorCylindricalMapper`.

The periodic mappers are needed to handle the results of simulations carried out with periodic boundary conditions, while the cylindrical mappers are needed to handle the functions defined in cylindrical coordinates.

For example, with the new mappers a 3D function defined in cylindrical coordinates on a 20° toroidal sector can be mapped with:
```python
CylindricalMapper(PeriodicMapper3D(function, 0, np.pi / 9, 0))
```
and a vector function can be mapped with:
```python
VectorCylindricalMapper(VectorPeriodicMapper3D(vector_function, 0, np.pi / 9, 0))
```

### CODE REVIEW

**Comment by vsnever** [comment]
I agree, let's move these to `cherab.math.transform` and rename to `CylindricalTransform`, `PeriodicTransformXD` etc.

**Comment by vsnever** [comment]
The functions are renamed to `PeriodicTransform#D`, `VectorPeriodicTransform#D`, `CylindricalTransform` and `VectorCylindricalTransform` and moved to `cherab.math.transform`. The docs are updated to include the new `cherab.math.transform` sub-module.

**Comment by jacklovell** [comment]
Looks good. Can you add unit tests for the `VectorPeriodic*Transform` classes? The scalar classes have tests but the vector classes are missing them.

(By the way, test coverage can be checked by installing recent versions of Cython and Coverage and running `./dev/build.sh --line-profile && coverage run -m unittest && coverage report` (with optional `coverage html` for easier navigation).

**Comment by vsnever** [comment]
Thanks for the review, @jacklovell. I've added tests for the `VectorPeriodicTransform` functions.

**Comment by jacklovell** [comment]
Thanks. Looks good to me now.

**Pull request merged**
