### PR TITLE
Add Raysect 0.8 compatibility

### PR DESCRIPTION
**Pull request by vsnever**
Raysect 0.8 has been released, so since the development branch should build against Raysect's master, the `raysect-0.8-compat` branch is ready to be merged into development.

### CODE REVIEW

**Comment by vsnever** [comment]
Yes, that's probably right. I'll leave this PR open for the future though.

**Comment by jacklovell** [comment]
Now that Cherab 1.4.0 is out I think we can look at updating the development branch for raysect 0.8. Tests all pass: any objections to the merge?

**Review by Mateasek — APPROVED** [review]

**Comment by Mateasek** [comment]
not from my side, thanks

**Comment by vsnever** [comment]
Just one thing, can we temporarily specify that we need `matplotlib<=3.5.3`, because [this](https://github.com/raysect/source/issues/383) `set_window_title()` issue was fixed only in Raysect 0.8.1, which is not yet released?

**Comment by jacklovell** [comment]
Not too keen on working around raysect's bugs, but in this case setting a limit on the matplotlib version does seem like a pragmatic solution. I'll make the change.

**Comment by CnlPepper** [comment]
I'll release Raysect v0.8.1 this weekend, if I get time.

**Comment by jacklovell** [comment]
Thanks @CnlPepper. In that case I propose we wait until 0.8.1 is out and then just support that going forwards. I can't see anything in the 0.8.1 changelog that would affect Cherab: there are no instances of `extract_translation` or `extract_rotation` in Cherab's source code.

**Comment by CnlPepper** [comment]
@jacklovell I've released Raysect 0v.8.1. It fixes a number of niggling issues, such as the deprecated matplotlib window title call.

**Comment by vsnever** [comment]
@jacklovell, should we add the `-O3` compilation flag like Raysect 0.8.1 does?

**Comment by CnlPepper** [comment]
I'd recommend you do. Anaconda and other python distributions seem to have changed their defaults to -o2, which results in a performance drop.

**Comment by jacklovell** [comment]
Interesting. Manylinux still uses `-O3` which is what I build the PyPI wheels on, so forcing the use of `-O3` in setup.py shouldn't make a difference for most users. I'll make this change and then merge.

**Pull request merged**
