### PR TITLE
Fix: Set plasma b_field and distribution default values

### PR DESCRIPTION
**Pull request by Mateasek**
None default values in plasma can cause segmentation fault
Added ZeroDistribution returning zero values
On default b_field is set to Vector3D(0, 0, 0)
On default electron_distribution is set to ZeroDistribution

### CODE REVIEW

**Comment by Mateasek** [comment]
Related to #231

**Comment by Mateasek** [comment]
Is there anything else to be changed @CnlPepper , @jacklovell ?

**Comment by jacklovell** [comment]
Nothing my end.

**Comment by CnlPepper** [comment]
All good, happy to merge.

**Pull request merged**
