### PR TITLE
Feature/generomak firstwall

### PR DESCRIPTION
**Pull request by Mateasek**
This PR adds first wall components to Generomak and is related to #212.

The components are saved in obj files and contain also vertex normals. I generated the meshes in Salome from 3D models made in Catia. The vertex normals were generated post-meshing in Mesh lab.

My huge thanks goes to Vojtech Balner, who created the tile models.

The first wall is created by distributing toroidally and vertically instances of the meshes contained in the obj files.

### CODE REVIEW

**Comment by vsnever** [comment]
Thank you very much for this PR, @Mateasek.
Since we are going to add several synthetic diagnostics for the Generomak in the future, I think it will be more convenient to add it as a submodule (cherab/generomak/machine), like the Cherab modules for real devices (JET, Compass, MAST-U), than as a separate demo file.

**Comment by Mateasek** [comment]
I thought that the idea was to have it in core, so you download it with demos based on Generomak.

**Comment by vsnever** [comment]
> I thought that the idea was to have it in core, so you download it with demos based on Generomak.

I am not suggesting moving it from Cherab core, on the contrary I think that it should be a part of the Cherab package itself, just like the openadas module, rather than a part of the demos. Since we will have several synthetic diagnostics and a lot of demos based on these diagnostics, I think it would be more convenient to import the wall mesh and the diagnostics like:
```python
from cherab.generomak.machine import *
from cherab.generomak.cxrs import *
```

**Comment by Mateasek** [comment]
Right I understand now. For some reason I thought you wanted to have it in a separate repository. I am not sure, I don't have any preference here. Moving it to separate repo would probably result in a simpler folder tree and it could also show the users how to design their own packages. On the other hand there will be also demos not relying on Generomak and then you will have two locations with demos, but that might not be an issue. I think here @mattngc, @CnlPepper, @vsnever should also express their opinion.

**Comment by jacklovell** [comment]
The generomak data should live in this repository. The files themselves, and helper routines to load them, should be within the cherab package itself, perhaps under `cherab.generomak` (though could also live somewhere like `cherab.tools.generomak`, similar to the already-existing `cherab.tools.equilibrium.example_equilibrium`). We should make sure the hierarchy permits the addition of other bits of generomak such as the magnetic equilibrium, profiles and diagnostics. Perhaps the wall should live in `cherab.generomak.vessel`, then we could additionally have `cherab.generomak.equilibrium`, `cherab.generomak.profiles` and `cherab.generomak.observers`.

The helper routine `load_first_wall` should certainly be importable. Demo scripts which go in `demos` should use these routines to load the generomak machine and make plasmas, but the demos do not need to be importable themselves: they're expected to be run standalone.

I'll also add that a full discussion of the filesystem layout for these components is best done in #209.

**Comment by mattngc** [comment]
Really nice work @Mateasek, I agree with the comments above. This data should live in this repository so that we can base all our demos off it. I like the suggestions from @vsnever and @jacklovell, both `cherab.generomak` and `cherab.tools.generomak` seem like sensible locations. These folders should contain the importable functions and data, while the actually generomak demo scripts should be in their own folder hierarchy under the demos folder.

**Comment by Mateasek** [comment]
I agree, the listed points are very good, I applied these changes:
I created the cherab/generomak folder.
The files and folders were moved to cherab/generomak/machine

**Pull request merged**
