### PR TITLE
Correct the get_wavelength() call in beam_emission_pec()

### PR DESCRIPTION
**Pull request by vsnever**
This is a hotfix for #259.

### CODE REVIEW

**Review by mattngc — APPROVED** [review]
Thanks Vlad, looks good.

**Comment by vsnever** [comment]
Looks like Travis CI is hung and will never report the status, just like in PR #246.

**Comment by mattngc** [comment]
Ah, that's annoying. I was waiting for it to pass before merging. Going to bed now, but I'll try to investigate it in Travis with @CnlPepper tomorrow morning. Even though its a one line fix, better to have it pass instead of doing a forced merge.

**Comment by CnlPepper** [comment]
Odd, not sure why travis has failed, I'll take a look.

**Comment by CnlPepper** [comment]
So it looks like travis is no longer totally free and we have run out of our "free" credit. They have just introduced a new billing system.

**Comment by CnlPepper** [comment]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by CnlPepper** [comment]
I'll turn travis off for now, we'll need t consider an alternative or start paying.

**Comment by mattngc** [comment]
Ok, thanks for investigating, sounds like the ideal time to investigate github actions as an alternative.

**Pull request merged**
