### PR TITLE
Fix periodicity check in ray transfer objects for cylindrical grids

### PR DESCRIPTION
**Pull request by vsnever**
This is a fix for #225.

### CODE REVIEW

**Comment by vsnever** [comment]
Failed due to this:
`ERROR: No matching distribution found for raysect==0.7`

**Comment by jacklovell** [comment]
Thanks for this Vlad. That error is expected: cherab development branch now depends on raysect development branch (the function framework was updated in a backwards-incompatible way) and the latter isn't yet available on PyPI. As long as the unit tests pass on a local checkout of both repos this will  be fine to merge.

**Comment by jacklovell** [comment]
The check should be fixed now. Could you rebase this PR onto development? I'm happy to merge it once it passes CI.

**Comment by vsnever** [comment]
> The check should be fixed now. Could you rebase this PR onto development? I'm happy to merge it once it passes CI.

Thank you. It's done.

**Pull request merged**
