### PR TITLE
Fix Discrete2DMesh import

### PR DESCRIPTION
**Pull request by Mateasek**
Discrete2D moved from location "from raysect.core.math.interpolators cimport Discrete2DMesh"  to "from raysect.core.math.function cimport Discrete2DMesh"

this should make development branches of Raysect and CHERAB compatible

linked to #175

### CODE REVIEW

**Comment by Mateasek** [comment]
Cheers, I've changed the import to import the Function2D from Raysect as pointed out.

**Comment by jacklovell** [comment]
Thanks. I have one last request, which I've just noticed from looking at the build log: this now technically depends on `raysect>=0.6.0`, but the Travis config and pip installer data still say the project requires an older raysect version 0.5.6. Your build got lucky and got away with this because the most recent raysect was pulled in, but installation will fail for users who already have raysect 0.5.6 installed and try to install the latest cherab.

Could you please modify setup.py, requirements.txt and .travis.yml to point to the latest version of raysect? This should then be good to merge.

**Comment by Mateasek** [comment]
Good spot, I changed the setup.py to require raysect >= 0.6.0

**Comment by jacklovell** [comment]
Thanks. How about requirements.txt and .travis.yml? Both also still point to the older raysect version.

**Comment by Mateasek** [comment]
I am not really making it straightforward, am I? Added also changes to .travis.yml and requirements.txt

**Comment by jacklovell** [comment]
Perfect, thanks. @mattngc are you happy to merge this? We'll need to rebase all other open PRs onto development after this is merged, to ensure they build properly.

**Pull request merged**
